# Generated by Django 3.2.12 on 2023-12-21 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Snack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(max_length=250)),
                ('prep_time', models.PositiveIntegerField(db_column='Prepartion Time', help_text='Enter the time it takes to prepare the snack/food.')),
            ],
        ),
    ]
