# Generated by Django 3.2.12 on 2023-12-22 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Taste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='snack',
            name='prep_time',
            field=models.PositiveIntegerField(db_column='Prepartion Time', help_text='Enter the time it takes to prepare the snack/food in minutes.'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('comment', models.TextField(max_length=250)),
                ('snack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.snack')),
            ],
        ),
        migrations.AddField(
            model_name='snack',
            name='tastes',
            field=models.ManyToManyField(to='main_app.Taste'),
        ),
    ]
