# Generated by Django 3.2.12 on 2023-12-22 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20231222_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='taste',
            name='description',
            field=models.TextField(default='Tasting of, containing, or preserved with salt.', max_length=100),
            preserve_default=False,
        ),
    ]
